In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/AB_NYC_2019.csv")
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0

In [ ]:
df.price.describe()

count    7390.000000
mean      167.145873
std       278.992369
min        10.000000
25%        80.000000
50%       120.000000
75%       185.000000
max      9999.000000
Name: price, dtype: float64

In [ ]:
min_thresold, max_thresold = df.price.quantile([0.01,0.999])
min_thresold, max_thresold

(35.0, 4305.500000000393)

In [ ]:
df[df.price<min_thresold]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
469,165824,Lady only Curtain-divided room,733894,Lucy,Queens,Sunnyside,40.74000,-73.91901,Private room,33.0,44.0,31.0,2019-05-01,0.32,3.0,161.0
747,270315,Bed-stuy Royal Room,1398639,Juliet,Brooklyn,Bedford-Stuyvesant,40.68812,-73.93254,Private room,34.0,10.0,16.0,2019-03-27,0.19,3.0,216.0
776,278145,Large Room in a Huge NY apartment.,1452026,Heidi,Queens,Astoria,40.77117,-73.91905,Private room,30.0,5.0,3.0,2017-06-20,0.03,1.0,0.0
845,296844,"HISTORIC WILLIAMSBURG, BKLYN #1",839679,Brady,Brooklyn,Williamsburg,40.71653,-73.95554,Private room,30.0,3.0,24.0,2013-12-04,0.28,3.0,0.0
957,375249,Enjoy Staten Island Hospitality,1887999,Rimma & Jim,Staten Island,Graniteville,40.62109,-74.16534,Private room,20.0,3.0,80.0,2019-05-26,0.92,1.0,226.0
1965,858695,Very Large Private Room on quiet st,4494343,Douglas,Bronx,Mount Eden,40.84058,-73.91382,Private room,30.0,2.0,291.0,2019-06-20,3.69,1.0,208.0
2062,924658,"Bright, airy room share in Brooklyn",4973668,Gloria,Brooklyn,Bedford-Stuyvesant,40.68700,-73.93446,Shared room,30.0,5.0,91.0,2019-06-01,1.18,3.0,248.0
2675,1428154,"Central, Peaceful Semi-Private Room",5912572,Tangier,Brooklyn,Flatbush,40.63899,-73.95177,Shared room,29.0,2.0,5.0,2014-10-20,0.07,1.0,321.0
2860,1620248,Large furnished 2 bedrooms- - 30 days Minimum,2196224,Sally,Manhattan,East Village,40.73051,-73.98140,Entire home/apt,10.0,30.0,0.0,NaN,NaN,4.0,137.0
2887,1652236,Amazing Spacious Room,3562322,Lord Daniel,Brooklyn,Bedford-Stuyvesant,40.68708,-73.95126,Private room,31.0,6.0,41.0,2019-07-03,0.58,3.0,55.0
3020,1767037,Small Cozy Room Wifi & AC near JFK,9284163,Antonio,Queens,Woodhaven,40.68968,-73.85219,Private room,29.0,2.0,386.0,2019-06-19,5.53,3.0,50.0
3165,1886978,Sunny & Budget Friendly,9522524,Nancy,Brooklyn,Canarsie,40.64674,-73.89501,Private room,32.0,5.0,85.0,2019-06-16,1.25,5.0,155.0
3313,1979744,Bright & Budget Friendly,9522524,Nancy,Brooklyn,Canarsie,40.64605,-73.89382,Private room,33.0,5.0,84.0,2019-06-27,1.25,5.0,295.0
3390,2030736,Room B,10384906,Susan,Brooklyn,Sunset Park,40.64532,-74.02063,Private room,32.0,1.0,111.0,2019-04-20,1.70,5.0,208.0
3395,2036105,Private room D,10384906,Susan,Brooklyn,Dyker Heights,40.62830,-74.01608,Private room,30.0,1.0,67.0,2019-01-22,0.99,5.0,150.0
3517,2102344,Cozy Private Room in Artsy Bushwick,5976214,Angela,Brooklyn,Bushwick,40.70381,-73.92766,Private room,30.0,3.0,2.0,2014-01-03,0.03,1.0,0.0
3558,2124910,Private Room E,10384906,Susan,Brooklyn,Borough Park,40.63592,-74.00476,Private room,33.0,1.0,98.0,2019-06-16,1.55,5.0,0.0
3705,2234100,"Coffee,Tea&Milk Astor Place Lodging",10931680,John,Manhattan,East Village,40.72672,-73.98851,Shared room,30.0,30.0,125.0,2017-12-31,1.88,1.0,304.0
3889,2392296,"A Simple, Calm Space",10510181,Août,Bronx,Kingsbridge,40.88437,-73.89746,Shared room,32.0,2.0,6.0,2016-09-22,0.16,1.0,83.0
3903,2414157,Relaxed Comfortable Beds in A Cozy Apartment.,8904815,Sandra&Orlando,Brooklyn,Flatbush,40.64307,-73.95455,Shared room,30.0,5.0,34.0,2019-06-29,0.52,2.0,288.0
3918,2431607,"Bright, Airy Room Share for 2",4973668,Gloria,Brooklyn,Bedford-Stuyvesant,40.68642,-73.93440,Shared room,25.0,5.0,76.0,2019-06-06,1.22,3.0,258.0
3950,2459916,"$455 Cozy 1bd, BKLYN Sublet March",12577771,Victor,Brooklyn,Bedford-Stuyvesant,40.68948,-73.93528,Private room,18.0,1.0,0.0,NaN,NaN,1.0,0.0
3975,2477138,Private Room: The cheapest deal!!,9089934,Siddharth,Queens,Ozone Park,40.67948,-73.85335,Private room,30.0,7.0,0.0,NaN,NaN,1.0,0.0
4047,2563764,Huge room in South Prospect Park,13125674,Yago,Brooklyn,Flatbush,40.64576,-73.95871,Private room,30.0,15.0,1.0,2018-06-20,0.08,1.0,0.0
4068,2592640,Great room with awesome amenities!,13272957,Johnny,Brooklyn,Bedford-Stuyvesant,40.69135,-73.94694,Private room,30.0,1.0,1.0,2014-03-28,0.02,1.0,0.0
4096,2632699,Budge private room F,10384906,Susan,Brooklyn,Borough Park,40.63081,-73.99638,Private room,31.0,1.0,60.0,2019-04-01,0.97,5.0,158.0
4425,3010988,Big Private room in Brooklyn Brownstone,13208084,Sheki,Brooklyn,Crown Heights,40.67690,-73.94483,Private room,32.0,7.0,3.0,2018-06-15,0.07,3.0,319.0
4529,3139489,"Nice Cozy Room in BROOKLYN, NYC, NY, Bushwick",2885704,Victor,Brooklyn,Bushwick,40.69545,-73.91967,Private room,33.0,2.0,182.0,2019-06-21,3.62,2.0,16.0
4647,3258197,Large 1br Duplex in Heart of Upper East Side,16477306,Jeff,Manhattan,Upper East Side,40.76866,-73.95553,Entire home/apt,16.0,2.0,21.0,2019-06-30,1.69,1.0,9.0
4751,3359315,Sublet near Columbia University,16948705,Berhani,Manhattan,Harlem,40.81742,-73.95358,Private room,22.0,10.0,3.0,2015-08-08,0.05,1.0,0.0
4757,3368427,Happy big family,4044499,Alexander,Brooklyn,Flatbush,40.65287,-73.96353,Private room,30.0,1.0,0.0,NaN,NaN,1.0,0.0
5052,3627589,Cozy Single private room.,3562322,Lord Daniel,Brooklyn,Bedford-Stuyvesant,40.68599,-73.95182,Private room,34.0,6.0,81.0,2019-07-04,1.35,3.0,92.0
5287,3819946,Great cozy in Brooklyn,20169857,Fabeye & Nabou,Brooklyn,Bedford-Stuyvesant,40.69634,-73.94410,Private room,33.0,1.0,52.0,2019-04-08,0.87,2.0,255.0
5542,4031809,Prewar classic NYC apartment.,20902552,Miquel,Manhattan,Washington Heights,40.83456,-73.94344,Private room,16.0,14.0,0.0,NaN,NaN,1.0,0.0
5627,4093591,1 Room & 1 Bath,11090576,Michael,Brooklyn,Bushwick,40.69216,-73.90859,Private room,25.0,1.0,8.0,2015-01-15,0.14,1.0,0.0
5713,4162519,Happy cozy Manchi GUEST ROOM,1267556,Mari J,Brooklyn,Flatbush,40.63995,-73.96196,Shared room,30.0,1.0,81.0,2019-06-29,1.39,1.0,319.0
5847,4265471,Ladies Shared Dorm Room (Top Bunk),3294438,Torell,Brooklyn,Bedford-Stuyvesant,40.68676,-73.95801,Shared room,30.0,2.0,13.0,2019-07-01,0.37,3.0,339.0
6108,4472904,Dorm Sz Room. Near 2 & 5 train 180 st Bronx zoo,1532337,Monica,Bronx,Van Nest,40.84230,-73.87055,Private room,25.0,30.0,6.0,2019-05-28,0.17,4.0,219.0
6179,4519764,Private Space in Manhattan 8/25-9/9,16310013,Tan,Manhattan,Washington Heights,40.85181,-73.93824,Private room,29.0,7.0,0.0,NaN,NaN,1.0,0.0
6351,4633258,Room 15 min from Manhttn.,23993707,Bogna,Queens,Woodside,40.74626,-73.89727,Private room,30.0,5.0,2.0,2017-12-29,0.04,2.0,0.0
6518,4730371,Hipster-Chic Bushwick Apartment,6898927,Sarah,Brooklyn,Bushwick,40.69738,-73.91162,Private room,33.0,2.0,9.0,2019-01-01,0.19,1.0,0.0
6571,4758601,Sunny Room in Charming Bed-stuy Apartment,24554369,Laina,Brooklyn,Bedford-Stuyvesant,40.68778,-73.92484,Private room,31.0,5.0,1.0,2015-08-01,0.02,1.0,0.0
6615,4777166,"Super Clean, Quiet & Spacious Room",24636847,Troy,Queens,Woodhaven,40.69634,-73.85630,Private room,31.0,3.0,3.0,2018-07-11,0.23,1.0,0.0
6635,4784846,1 BR in loft / Bushwick,24667595,Pierre,Brooklyn,Bushwick,40.69169,-73.92351,Private room,30.0,1.0,8.0,2017-06-25,0.15,1.0,0.0
6992,5021376,Easily accessible cozy room! R202,17638424,Sophie,Queens,Elmhurst,40.74602,-73.87338,Private room,34.0,1.0,95.0,2019-07-02,2.37,8.0,175.0
7097,5132306,Monthly Rental in Crown Heights,24711354,Forrest,Brooklyn,Crown Heights,40.66809,-73.93373,Private room,33.0,28.0,20.0,2019-04-06,0.37,1.0,282.0
7129,5181720,Bushwick Live/Work,5399418,Jennifer,Brooklyn,Bushwick,40.69092,-73.90443,Private room,30.0,1.0,0.0,NaN,NaN,1.0,0.0
7279,5352301,Housing for SGU/AUA/SABA/ROSS students,27741331,Lyn,Brooklyn,East Flatbush,40.65777,-73.92263,Private room,27.0,30.0,9.0,2019-03-23,0.18,2.0,345.0
7313,5385943,Spacious Room in Awesome Apt Sublet,27919611,Matthew,Manhattan,Washington Heights,40.83242,-73.93931,Private room,28.0,20.0,0.0,NaN,NaN,1.0,0.0

In [ ]:
df2 = df[(df.price>min_thresold)&(df.price<max_thresold)]
df2.shape

(48183, 16)

In [ ]:
df2.sample(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
33361,26357960,Soho Loft,117086989,Robert,Manhattan,SoHo,40.72292,-74.00456,Entire home/apt,300,1,0,NaN,NaN,1,0
19013,15099669,Lower East Side large 1 bedroom,95608415,Cory,Manhattan,Lower East Side,40.71975,-73.98608,Entire home/apt,225,1,2,2016-10-20,0.06,1,0
10945,8444013,Cozy Wkd Getaway Spot in Prime BK,11625123,Jennifer,Brooklyn,Crown Heights,40.67501,-73.95873,Entire home/apt,95,2,20,2019-04-26,0.44,1,0
6887,4925368,Great Room with Good Amenities,331579,Marlon,Brooklyn,Bedford-Stuyvesant,40.68744,-73.92322,Private room,60,3,29,2019-06-04,0.60,2,232
12329,9519514,NYC Town House,3338222,Damian,Manhattan,West Village,40.73837,-74.00586,Entire home/apt,1200,6,1,2019-01-04,0.16,1,290

In [ ]:
df2.price.describe()

count    48183.000000
mean       148.772036
std        153.594795
min         31.000000
25%         70.000000
50%        110.000000
75%        179.000000
max       2999.000000
Name: price, dtype: float64